2.7.4
oetiker/SmokePing pull request #278
Opened 2021-05-18 09:22 UTC by deveshmanish

* Increased Slave polling timeout from 60s to 300s to give slaves ample time to poll multiple targets.
    * Added additional probes: 
        * speedtest.pm - Ookla official speedtest client
        * speedtest-cli.pm - Sievel's speedtest-cli
        * YoutubeDL.pm - YoutubeDL probe
        * WifiParam.pm - WiFi parameter probe with iw

2021-05-18 11:43 UTC, oetiker requested changes

2021-05-18 11:43 UTC, oetiker commented on VERSION
> +2.7.4
```suggestion
2.7.3
```
please do not change the release

2021-05-18 11:43 UTC, oetiker commented on lib/Smokeping.pm
> +$VERSION="2.7.4";
```suggestion
$VERSION="2.006000";
```

please do not change the release

2021-05-18 11:56 UTC, oetiker commented
I see that the additional probes have been created by @mad-ady. Wondering why he is not contributing them himself.

2021-05-18 12:21 UTC, deveshmanish commented
> I see that the additional probes have been created by @mad-ady. Wondering why he is not contributing them himself.

@mad-ady might be able to shed some light on that. In view of getting the process expedited, I had proposed this PR as I have been using this patched work for long and hoped this would make things simpler.

2021-05-18 12:44 UTC, mad-ady commented
Sorry - I didn't contribute them because I didn't think they would be useful for the general public, so I kept them separate. Over the years some people asked questions about speedtest especially. 

The probes (speedtest/youtube-dl) depend on external binaries some of which might change often and need updating, and also, the probes themselves bypass the normal smokeping measurement process by doing only one measurement and reporting 3 identical measurements. This is in order to prevent too much resource utilization/getting banned on those services for being too aggressive. There are also some limitations with regard to the unit of measurement reported. By default smokeping likes to measure time on the y axis, but these probes measure traffic/DB/MHz. If @oetiker doesn't mind with this hack, then fine!

I don't mind having this PR merged, even if it's not submitted by me. Though I'm not sure if the code is from my repos directly, or had some changes.

Cheers!

2021-05-19 14:30 UTC, oetiker commented
@mad-ady reporting the same measurment multiple times seems rather odd to me ... how about complaining if pings is more than 1?

2021-05-19 15:08 UTC, mad-ady commented
Unfortunately, that won't work because smokeping itself has a minimum limit
of 3 pings. Lowering that might break other internal processing, so I chose
to fake it :)

On Wed, May 19, 2021, 17:31 Tobias Oetiker ***@***.***> wrote:

> @mad-ady <https://github.com/mad-ady> reporting the same measurment
> multiple times seems rather odd to me ... how about complaining if pings is
> more than 1?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oetiker/SmokePing/pull/278#issuecomment-844161987>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABAO6KUE2MS6CQFSXOVOLBLTOPDSJANCNFSM45CD7KPA>
> .
>

2021-08-25 04:31 UTC, closed without merging