Proposed enhancement for #385 to allow IPv4 or IPV6 preference in SSH…
oetiker/SmokePing pull request #390
Opened 2023-12-05 19:28 UTC by FliesLikeABrick

Proposed enhancement for #385 to allow IPv4 or IPV6 preference in SSH probe, passing -4 or -6 to ssh-keyscan process.  Also with an option to override/reset parent section inheritance

2024-01-16 07:15 UTC, oetiker requested changes
please update the CHANGES file!

2024-01-29 15:16 UTC, FliesLikeABrick commented
Sorry @oetiker  just saw this - CHANGES has been updated

2024-02-02 08:36 UTC, oetiker approved these changes

2024-02-02 08:36 UTC, merged

2024-02-02 08:37 UTC, oetiker commented
thank you!