Add "literalsearch" option to filter targets using literal strings instead of regex
oetiker/SmokePing pull request #409
Opened 2024-08-04 09:10 UTC by jlu5

This is a continuation of #407: add an option to process Filter menu targets using literal strings instead of (partially supported) regex

2024-08-05 15:01 UTC, oetiker requested changes

2024-08-05 15:01 UTC, oetiker commented on lib/Smokeping.pm
> +			if ($cfg->{Presentation}{literalsearch} eq 'yes') {
```suggestion
			if (($cfg->{Presentation}{literalsearch} || 'no') eq 'yes') {
```

2024-08-06 07:02 UTC, oetiker approved these changes

2024-08-09 01:48 UTC, jlu5 commented
The PR is approved but not merged yet, is there anything I can do to push it along?

2024-08-09 06:54 UTC, oetiker commented
sorry, was waiting for the tets to go through :)

2024-08-09 06:55 UTC, merged